//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factura_CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int CodFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal ValorTotal { get; set; }
        public string Ciudad { get; set; }
    
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
    }
}
