//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sucursales_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int CodSucursal { get; set; }
        public int CodBanco { get; set; }
        public string DireccionSuc { get; set; }
        public string Nombre { get; set; }
    
        public virtual Banco Banco { get; set; }
    }
}
