//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Factura
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int CodDetalle { get; set; }
        public int CodFactura { get; set; }
        public string NombreProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorProducto { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
